### ISSUE TITLE
parseConnectionParams returns paramstring if parseValues is false

### ISSUE THREAD

**Issue by mlaanderson** [mlaanderson/database-js-common#2]
I would like to see the parseConnectionParams always return JSON. If the URL is ```mysql://user:password@localhost/data?supportBigNumbers=true&bigNumberStrings=true``` then when parseValues is false we should have JSON like this:
````JSON
{
    "supportBigNumbers":"true",
    "bigNumberStrings":"true"
}
````
But if parseValues is true then the JSON should be like this:
````JSON
{
    "supportBigNumbers":true,
    "bigNumberStrings":true
}
````

**Comment by pahan35** [comment]
@mlaanderson ok. I misunderstood your previous proposal. I'll fix it a bit later

**Comment by pahan35** [comment]
@mlaanderson I've fixed the issue
